# Generated by Django 4.1.7 on 2023-03-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Retinopathy', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technician',
        ),
    ]
