# Generated by Django 4.1.7 on 2023-04-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Retinopathy', '0004_delete_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('prediction', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
